# Security & Master Infrastructure Keys
ta.key=TA-KEY-9988
proxy.key=PROXY-KEY-7788
csp.key=CSP-KEY-5544
tdes.key=REENCRYPTIONDATAREENCRYPTIONDATA

# External Cloud Storage Provider (DriveHQ FTP)
ftp.host=ftp.drivehq.com
ftp.user=stubtechict@gmail.com
ftp.pass=StuBt3q!ct

